on: [push, pull_request]
permissions:
  contents: read
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [1.19.x, 1.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Vet
      run: go vet ./...
    - name: Staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
    - name: Test
      run: go test -v -race ./...

